# Generated by Django 5.2.14 on 2026-05-28 09:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='cycle name')),
                ('academic_year', models.CharField(max_length=20, verbose_name='academic year')),
                ('start_date', models.DateField(verbose_name='application open date')),
                ('end_date', models.DateField(verbose_name='application close date')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('max_applications', models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='max applications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'admission cycle',
                'verbose_name_plural': 'admission cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portal/news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('transfer', 'Transfer'), ('exchange', 'Exchange / Visiting')], default='undergraduate', max_length=20, verbose_name='application type')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('other_names', models.CharField(blank=True, max_length=150, verbose_name='other names')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not', 'Prefer not to say')], max_length=20, verbose_name='gender')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='nationality')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='residential address')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='previous school / institution')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='highest qualification')),
                ('year_of_completion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='year of completion')),
                ('aggregate_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='aggregate / GPA')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='admissions/transcripts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='transcript / results slip')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='admissions/ids/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='ID / passport')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/%Y/%m/', verbose_name='passport photograph')),
                ('personal_statement', models.TextField(blank=True, verbose_name='personal statement')),
                ('qualifications', models.TextField(blank=True, verbose_name='qualifications')),
                ('documents', models.FileField(blank=True, null=True, upload_to='portal/admissions/', verbose_name='documents')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('review', 'Under Review'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted'), ('withdrawn', 'Withdrawn by Applicant')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='reference number')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejected at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='applied at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('program_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.program', verbose_name='program applied for')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_applications', to=settings.AUTH_USER_MODEL, verbose_name='rejected by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.OneToOneField(blank=True, help_text='Created automatically on approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to=settings.AUTH_USER_MODEL, verbose_name='provisioned user account')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='portal.admissioncycle', verbose_name='admission cycle')),
            ],
            options={
                'verbose_name': 'admission application',
                'verbose_name_plural': 'admission applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='document required')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions to applicant')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('waived', 'Waived')], default='pending', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested at')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='fulfilled at')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='admissions/requested_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='uploaded document')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='portal.admissionapplication', verbose_name='application')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'document request',
                'verbose_name_plural': 'document requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['status', '-created_at'], name='portal_admi_status_ee1569_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['email'], name='portal_admi_email_86e698_idx'),
        ),
    ]
