# Generated by Django 5.2.14 on 2026-09-28 06:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_gradingscheme_progressionpolicy_gradeboundary_and_more'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable machine code, e.g. 'undergraduate'.", max_length=40, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop new applications of this type without affecting applications already in the system.', verbose_name='offered')),
                ('requires_program', models.BooleanField(default=True, help_text='If unticked, applicants of this type pick a programme later instead of at application time.', verbose_name='requires programme selection')),
                ('requires_payment', models.BooleanField(default=True, verbose_name='requires application fee')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'application type',
                'verbose_name_plural': 'application types',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='converted to student at'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_converted', to=settings.AUTH_USER_MODEL, verbose_name='converted by'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='correction_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='correction requested at'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('conditionally_accepted', 'Conditionally Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], db_index=True, default='pending', help_text='The academic outcome. Independent of the workflow status above.', max_length=25, verbose_name='admission decision'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decision made at'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='decision made by'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='decision_notes',
            field=models.TextField(blank=True, help_text='Internal remarks. Conditions attached to an offer belong on the offer.', verbose_name='decision notes'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='interview scheduled at'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interview_remarks',
            field=models.TextField(blank=True, verbose_name='interview remarks'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='last_correction_note',
            field=models.TextField(blank=True, help_text='Most recent reason staff asked the applicant to correct something.', verbose_name='last correction request'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='academic_session',
            field=models.ForeignKey(blank=True, help_text='The existing academic session applicants will be admitted into.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_cycles', to='academics.academicsession', verbose_name='academic session'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = no application fee for this cycle.', max_digits=10, verbose_name='application fee'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='payment_required_to_progress',
            field=models.BooleanField(default=True, help_text='When ticked, an application only moves past payment confirmation once the application fee is verified.', verbose_name='payment required before review'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', help_text='Only OPEN cycles accept new applications.', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('mature', 'Mature Applicant'), ('transfer', 'Transfer Applicant'), ('international', 'International Applicant'), ('distance_learning', 'Distance Learning'), ('exchange', 'Exchange / Visiting')], default='undergraduate', max_length=20, verbose_name='application type'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('payment_pending', 'Awaiting Payment'), ('payment_confirmed', 'Payment Confirmed'), ('under_review', 'Under Review'), ('needs_correction', 'Needs Correction'), ('resubmitted', 'Resubmitted'), ('shortlisted', 'Shortlisted'), ('interview_required', 'Interview Required'), ('interview_completed', 'Interview Completed'), ('decision_pending', 'Awaiting Decision'), ('completed', 'Completed'), ('converted', 'Converted to Student'), ('pending', 'Pending Review'), ('review', 'Under Review'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted'), ('withdrawn', 'Withdrawn by Applicant')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='application_type_ref',
            field=models.ForeignKey(blank=True, help_text='Auto-resolved from the application type code on save. Links the application to its configurable requirements.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='portal.applicationtype', verbose_name='application type (configured)'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='portal.applicationtype', verbose_name='application type'),
        ),
        migrations.CreateModel(
            name='AdmissionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='offer number')),
                ('admission_type', models.CharField(default='full_time', help_text='e.g. full_time, part_time.', max_length=30, verbose_name='admission type')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='issue date')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('status', models.CharField(choices=[('issued', 'Awaiting Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='issued', max_length=10, verbose_name='status')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='acceptance date')),
                ('conditions', models.TextField(blank=True, help_text='Conditions the applicant must satisfy, e.g. for a conditional offer.', verbose_name='conditions')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_offers', to='academics.academicsession', verbose_name='academic session')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_offers', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='portal.admissionapplication', verbose_name='application')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_offers_issued', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_offers', to='academics.program', verbose_name='programme')),
            ],
            options={
                'verbose_name': 'admission offer',
                'verbose_name_plural': 'admission offers',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['application', 'status'], name='portal_admi_applica_9014ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Application created'), ('updated', 'Details updated'), ('submitted', 'Submitted'), ('status_changed', 'Status changed'), ('payment_recorded', 'Payment recorded'), ('payment_confirmed', 'Payment confirmed'), ('document_uploaded', 'Document uploaded'), ('document_verified', 'Document verified'), ('document_rejected', 'Document rejected'), ('correction_requested', 'Correction requested'), ('decision_recorded', 'Admission decision recorded'), ('offer_issued', 'Offer issued'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('offer_expired', 'Offer expired'), ('converted', 'Converted to student'), ('withdrawn', 'Withdrawn by applicant')], db_index=True, max_length=30, verbose_name='action')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='to status')),
                ('remark', models.TextField(blank=True, verbose_name='remark')),
                ('is_visible_to_applicant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='portal.admissionapplication', verbose_name='application')),
            ],
            options={
                'verbose_name': 'application audit entry',
                'verbose_name_plural': 'application audit entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='portal_appl_applica_9c2444_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('transcript', 'Academic Transcript / Results Slip'), ('id_document', 'ID / Passport'), ('passport_photo', 'Passport Photograph'), ('birth_certificate', 'Birth Certificate'), ('wa_ssce_slip', 'WASSCE / SSSCE Slip'), ('degree_certificate', 'Degree Certificate'), ('cv', 'Curriculum Vitae'), ('reference', 'Reference Letter'), ('statement_of_purpose', 'Statement of Purpose'), ('research_interest', 'Research Interest'), ('other', 'Other Supporting Document')], default='other', max_length=40, verbose_name='document type')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='label')),
                ('file', models.FileField(upload_to='admissions/applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='file')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_replacement', 'Requires Replacement')], db_index=True, default='pending', max_length=25, verbose_name='verification status')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Increments each time the applicant supplies a replacement.', verbose_name='version')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='portal.admissionapplication', verbose_name='application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_documents_verified', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'application document',
                'verbose_name_plural': 'application documents',
                'ordering': ['document_type', '-uploaded_at'],
                'indexes': [models.Index(fields=['application', 'document_type'], name='portal_appl_applica_7c191f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_reference', models.CharField(help_text='Our reference for this payment attempt.', max_length=100, unique=True, verbose_name='payment reference')),
                ('provider', models.CharField(blank=True, help_text='e.g. paystack, cash, bank transfer, mobile money.', max_length=30, verbose_name='provider')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='provider transaction id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.admissionapplication', verbose_name='application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_payments_verified', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'application payment',
                'verbose_name_plural': 'application payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='portal_appl_applica_24518c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('field', 'Information field'), ('document', 'Supporting document')], default='document', max_length=10, verbose_name='requirement kind')),
                ('code', models.SlugField(help_text='For fields: the model field name. For documents: the document type code.', max_length=60, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('help_text', models.CharField(blank=True, max_length=250, verbose_name='help text')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='order')),
                ('program', models.ForeignKey(blank=True, help_text='Leave empty to apply to every programme of this type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_requirements', to='academics.program', verbose_name='programme (optional)')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='portal.applicationtype', verbose_name='application type')),
            ],
            options={
                'verbose_name': 'application requirement',
                'verbose_name_plural': 'application requirements',
                'ordering': ['application_type', 'kind', 'order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('application_type', 'program', 'kind', 'code'), name='uniq_requirement_per_type_program')],
            },
        ),
    ]
