# Generated by Django 5.2.15 on 2026-09-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_gradingscheme_progressionpolicy_gradeboundary_and_more'),
        ('portal', '0003_cycleapplicationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_links', to='portal.applicationtype', verbose_name='application type')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_type_links', to='academics.program', verbose_name='programme')),
            ],
            options={
                'verbose_name': 'programme application type',
                'verbose_name_plural': 'programme application types',
                'ordering': ['application_type__order', 'application_type__code'],
                'constraints': [models.UniqueConstraint(fields=('program', 'application_type'), name='uniq_program_application_type')],
            },
        ),
    ]
