# Generated by Django 5.2.15 on 2026-09-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrolment_is_retake_enrolment_original_enrolment'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicevent',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institution owning the event. Left blank when no institution is configured yet — such events are global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_events', to='academics.institution', verbose_name='institution'),
        ),
    ]
