# Generated by Django 5.2.14 on 2026-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_academicevent_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicschedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('under_review', 'Under Review'), ('hod_approved', 'HOD Approved'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('revision', 'Revision Required'), ('archived', 'Archived')], db_index=True, default='draft', max_length=15, verbose_name='status'),
        ),
    ]
