# Generated by Django 5.1.15 on 2026-06-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationrequest',
            name='is_retake',
            field=models.BooleanField(default=False, verbose_name='retake'),
        ),
    ]
