# Generated by Django 5.2.14 on 2026-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_courseregistrationrequest_is_retake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotification',
            name='category',
            field=models.CharField(choices=[('result', 'Result Published'), ('assignment', 'Assignment Posted'), ('quiz', 'Quiz Available'), ('material', 'New Material'), ('attendance', 'Attendance Alert'), ('general', 'General'), ('deadline', 'Deadline Reminder'), ('hostel', 'Hostel Management')], default='general', max_length=15),
        ),
    ]
