# Generated by Django 5.2.14 on 2026-07-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrolment_is_retake_enrolment_original_enrolment'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='retake fee amount')),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_fee_settings', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'retake fee setting',
                'verbose_name_plural': 'retake fee settings',
                'unique_together': {('session',)},
            },
        ),
        migrations.CreateModel(
            name='StudentRetakeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount due')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_fees', to='academics.course')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retake_fee_collections', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_retake_fees', to='academics.academicsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='retake_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student retake fee',
                'verbose_name_plural': 'student retake fees',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course', 'session')},
            },
        ),
    ]
