# Generated by Django 5.2.14 on 2026-05-28 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('teaching', 'Teaching Quality'), ('facilities', 'Facilities'), ('administration', 'Administration'), ('courses', 'Courses'), ('hostel', 'Hostel'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 star rating (optional)', null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='', max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Compound score from -1 (negative) to 1 (positive)', null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('admin_response', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
