# Generated by Django 5.2.14 on 2026-09-12 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_enrolment_is_retake_enrolment_original_enrolment'),
        ('finance', '0002_retakefeesetting_studentretakefee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='legacy capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=20, verbose_name='bed number')),
                ('label', models.CharField(blank=True, help_text='Human-friendly label, e.g. A203-03', max_length=120, verbose_name='label')),
                ('state', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=15, verbose_name='state')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='HostelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_open', models.DateField(blank=True, null=True, verbose_name='application opens')),
                ('application_close', models.DateField(blank=True, null=True, verbose_name='application closes')),
                ('allocation_open', models.DateField(blank=True, null=True, verbose_name='allocation opens')),
                ('allocation_close', models.DateField(blank=True, null=True, verbose_name='allocation closes')),
                ('reservation_expiry_hours', models.PositiveSmallIntegerField(default=48, help_text='Hours before an un-checked-in reservation expires.', verbose_name='reservation expiry hours')),
                ('require_payment_before_checkin', models.BooleanField(default=True, verbose_name='require payment before check-in')),
                ('allow_partial_payment', models.BooleanField(default=True, verbose_name='allow partial payment before check-in')),
                ('enable_hostel_charges', models.BooleanField(default=False, help_text='When enabled, allocations create StudentFee records in finance.', verbose_name='enable hostel charges')),
                ('allow_transfers', models.BooleanField(default=True, verbose_name='allow room transfers')),
                ('allow_hostel_transfers', models.BooleanField(default=True, verbose_name='allow hostel transfers')),
                ('require_active_student', models.BooleanField(default=True, verbose_name='require active student')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'hostel policy',
                'verbose_name_plural': 'hostel policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('checked_out', 'Checked Out')], db_index=True, default='reserved', max_length=15, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='allocation expires')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reserved at')),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='reservation expires at')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='allocated at')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='checked out at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='cancel reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_allocations_made', to=settings.AUTH_USER_MODEL, verbose_name='allocated by')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_allocations_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='checked in by')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_check_outs', to=settings.AUTH_USER_MODEL, verbose_name='checked out by')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='academics.academicsession', verbose_name='academic session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.hostelbed', verbose_name='bed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BedMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='ongoing', max_length=15, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_maintenance_completed', to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_maintenance_reported', to=settings.AUTH_USER_MODEL, verbose_name='reported by')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='hostel.hostelbed', verbose_name='bed')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hostel.hostel', verbose_name='hostel')),
            ],
            options={
                'ordering': ['hostel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the fee structure amount when set.', max_digits=12, null=True, verbose_name='amount payable')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('fee_structure', models.ForeignKey(blank=True, help_text='Finance fee structure used to generate StudentFee records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.feestructure', verbose_name='fee structure')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='hostel.hostel', verbose_name='hostel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_fee_configs', to='academics.academicsession', verbose_name='academic session')),
            ],
            options={
                'verbose_name': 'hostel fee config',
                'verbose_name_plural': 'hostel fee configs',
                'ordering': ['-session__start_date', 'hostel'],
            },
        ),
        migrations.CreateModel(
            name='HostelFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostel.hostelblock', verbose_name='block')),
            ],
            options={
                'ordering': ['block', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=20, verbose_name='room number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='legacy capacity')),
                ('is_available', models.BooleanField(default=True, verbose_name='administratively available')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hostel.hostelfloor', verbose_name='floor')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel', verbose_name='hostel')),
            ],
            options={
                'ordering': ['hostel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='HostelIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('room_damage', 'Room Damage'), ('misconduct', 'Misconduct'), ('lost_key', 'Lost Key'), ('unauthorized_occupancy', 'Unauthorized Occupancy'), ('disciplinary', 'Disciplinary Incident'), ('maintenance_complaint', 'Maintenance Complaint'), ('other', 'Other')], default='other', max_length=30, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=15, verbose_name='status')),
                ('resolution', models.TextField(blank=True, verbose_name='resolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='hostel.hostelallocation', verbose_name='allocation')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='hostel.hostelbed', verbose_name='bed')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents_reported', to=settings.AUTH_USER_MODEL, verbose_name='reported by')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_incidents', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='hostel.hostelroom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'hostel incident',
                'verbose_name_plural': 'hostel incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.hostelroom', verbose_name='room'),
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Submitted — Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved — Payment/Allocation Required'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed — Allocated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('admin_remark', models.TextField(blank=True, verbose_name='admin remark')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='payment verified at')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='hostel.hostelallocation', verbose_name='allocation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hostel_applications', to='academics.academicsession', verbose_name='academic session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hostel.hostelroom', verbose_name='preferred room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.hostelroom', verbose_name='room'),
        ),
        migrations.CreateModel(
            name='HostelTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_note', models.TextField(blank=True, verbose_name='review note')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_completed', to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('new_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_transfer', to='hostel.hostelallocation', verbose_name='new allocation')),
                ('new_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='hostel.hostelbed', verbose_name='new bed')),
                ('old_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='hostel.hostelallocation', verbose_name='old allocation')),
                ('old_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='hostel.hostelbed', verbose_name='old bed')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_transfers', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hostelblock',
            constraint=models.UniqueConstraint(fields=('hostel', 'name'), name='uniq_hostel_block'),
        ),
        migrations.AddConstraint(
            model_name='hostelfeeconfig',
            constraint=models.UniqueConstraint(fields=('hostel', 'session'), name='uniq_hostel_fee_config'),
        ),
        migrations.AddConstraint(
            model_name='hostelfloor',
            constraint=models.UniqueConstraint(fields=('block', 'name'), name='uniq_block_floor'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('hostel', 'room_number'), name='uniq_hostel_room'),
        ),
        migrations.AddConstraint(
            model_name='hostelbed',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='uniq_room_bed'),
        ),
        migrations.AddIndex(
            model_name='hostelapplication',
            index=models.Index(fields=['status', 'session'], name='hostel_host_status_1c22bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelapplication',
            index=models.Index(fields=['student', '-created_at'], name='hostel_host_student_36b520_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['student', 'status', 'session'], name='hostel_host_student_fb8fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['bed', 'status'], name='hostel_host_bed_id_f7f574_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['session', 'status'], name='hostel_host_session_300b25_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['reservation_expires_at'], name='hostel_host_reserva_31c89d_idx'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('reserved', 'active'))), fields=('student', 'session'), name='uniq_active_student_allocation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('reserved', 'active')), models.Q(('bed', None), _negated=True)), fields=('bed', 'session'), name='uniq_active_bed_allocation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_in__isnull', True), ('check_out__gte', models.F('check_in')), _connector='OR'), name='chk_allocation_checkout_after_checkin'),
        ),
    ]
