# Generated by Django 5.2.14 on 2026-09-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrolment_is_retake_enrolment_original_enrolment'),
        ('finance', '0002_retakefeesetting_studentretakefee'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Optional icon reference or emoji, e.g. 🧼', max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='hostelfeeconfig',
            name='uniq_hostel_fee_config',
        ),
        migrations.AddField(
            model_name='hostelfeeconfig',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave empty for a hostel-wide fee; set it to override the fee for a specific room (e.g. en‑suite surcharge).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='hostel.hostelroom', verbose_name='room override'),
        ),
        migrations.AddField(
            model_name='hostelfeeconfig',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave empty to apply to any semester (fallback); set it to charge per semester, e.g. 2026/2027 First Semester.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hostel_fee_configs', to='academics.semester', verbose_name='semester'),
        ),
        migrations.AddConstraint(
            model_name='hostelfeeconfig',
            constraint=models.UniqueConstraint(fields=('hostel', 'session', 'semester', 'room'), name='uniq_hostel_fee_config_scope', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='hostel.amenity', verbose_name='amenities'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hostel.amenity', verbose_name='amenities'),
        ),
    ]
