# Generated by Django 5.2.14 on 2026-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstaffrole',
            name='responsibility',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('dean', 'Dean / Faculty Head'), ('program_coordinator', 'Program Coordinator'), ('admissions_officer', 'Admissions Officer'), ('examinations_officer', 'Examinations Officer'), ('counselor', 'Student Counselor'), ('hostel_officer', 'Hostel Officer'), ('warden', 'Hostel Warden')], max_length=30, verbose_name='responsibility'),
        ),
    ]
