# Generated by Django 5.2.14 on 2026-09-17 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsheet',
            name='last_revised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last revised at'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='last_revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_sheets_revised', to=settings.AUTH_USER_MODEL, verbose_name='last revised by'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='last_revision_note',
            field=models.TextField(blank=True, help_text='Mandatory reason supplied when a published sheet was returned for correction.', verbose_name='last revision note'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published at'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_sheets_published', to=settings.AUTH_USER_MODEL, verbose_name='published by'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1, help_text='Publication round. Bumped each time a published sheet is revised.', verbose_name='revision'),
        ),
        migrations.CreateModel(
            name='ResultVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='revision')),
                ('sheet_status', models.CharField(blank=True, max_length=12, verbose_name='sheet status at snapshot')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='results snapshot')),
                ('note', models.TextField(blank=True, help_text='Reason supplied for this publication/revision round.', verbose_name='revision note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('result_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='teachers.resultsheet', verbose_name='result sheet')),
            ],
            options={
                'verbose_name': 'result version',
                'verbose_name_plural': 'result versions',
                'ordering': ['-revision'],
                'unique_together': {('result_sheet', 'revision')},
            },
        ),
    ]
