# Generated by Django 5.2.14 on 2026-09-22 21:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_gradingscheme_progressionpolicy_gradeboundary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('batch_number', models.CharField(max_length=24, unique=True, verbose_name='batch number')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('issued', 'Issued'), ('archived', 'Archived')], db_index=True, default='generated', max_length=12, verbose_name='status')),
                ('total_selected', models.PositiveIntegerField(default=0, verbose_name='students selected')),
                ('generated_count', models.PositiveIntegerField(default=0, verbose_name='cards generated')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='cards skipped')),
                ('skips', models.JSONField(blank=True, default=dict, verbose_name='skips detail')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='applied filters')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_batches_generated', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_batches', to='academics.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'ID card batch',
                'verbose_name_plural': 'ID card batches',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('validity_years', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='card validity (years)')),
                ('card_number_prefix', models.CharField(default='CARD', help_text='e.g. CARD → CARD-2026-000001', max_length=12, verbose_name='card number prefix')),
                ('verification_token_length', models.PositiveSmallIntegerField(default=32, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(64)], verbose_name='verification token length')),
                ('auto_renewal_enabled', models.BooleanField(default=False, help_text='When enabled, an expired card may be auto-replaced.', verbose_name='automatic renewal on expiry')),
                ('require_photo_approval', models.BooleanField(default=True, help_text='When unchecked, uploaded photos are treated as approved.', verbose_name='photo approval required')),
                ('allow_student_replacement_requests', models.BooleanField(default=True, verbose_name='students may request replacement')),
                ('verification_requires_login', models.BooleanField(default=False, help_text='Public QR verification is open unless this is enabled.', verbose_name='verification requires login')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_settings', to='academics.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'ID card setting',
                'verbose_name_plural': 'ID card settings',
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12, verbose_name='status')),
                ('is_default', models.BooleanField(default=False, help_text='Used for generation when no template is chosen explicitly.', verbose_name='default template')),
                ('card_width_mm', models.DecimalField(decimal_places=2, default=85.6, max_digits=5, verbose_name='card width (mm)')),
                ('card_height_mm', models.DecimalField(decimal_places=2, default=53.98, max_digits=5, verbose_name='card height (mm)')),
                ('primary_color', models.CharField(default='#1d4ed8', help_text='Hex colour, e.g. #1d4ed8.', max_length=7, verbose_name='primary colour')),
                ('secondary_color', models.CharField(default='#0f172a', max_length=7, verbose_name='secondary colour')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='text colour')),
                ('background', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/backgrounds/', verbose_name='card background image')),
                ('watermark', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/watermarks/', verbose_name='watermark image')),
                ('logo', models.ImageField(blank=True, help_text='Leave blank to use the institution logo.', null=True, upload_to='id_cards/templates/logos/', verbose_name='logo override')),
                ('front_fields', models.JSONField(default=list, verbose_name='front fields')),
                ('back_fields', models.JSONField(default=list, verbose_name='back fields')),
                ('custom_front_text', models.TextField(blank=True, verbose_name='front institution-defined text')),
                ('custom_back_text', models.TextField(blank=True, verbose_name='back institution-defined text')),
                ('return_instructions', models.TextField(blank=True, verbose_name='return instructions')),
                ('card_terms', models.TextField(blank=True, verbose_name='card terms')),
                ('authorized_signature_name', models.CharField(blank=True, help_text='Title / name printed under the authorized signature.', max_length=160, verbose_name='authorized signature name')),
                ('show_signature_line', models.BooleanField(default=True, verbose_name='show signature line')),
                ('validity_years', models.PositiveSmallIntegerField(default=4, help_text='Leave 0 to fall back to institution settings.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='validity (years)')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='academics.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'ID card template',
                'verbose_name_plural': 'ID card templates',
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PassportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(help_text='Recent passport photograph (JPG/PNG).', upload_to='id_cards/photos/%Y/%m/', verbose_name='passport photograph')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_photo_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='id_photo', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'passport photo',
                'verbose_name_plural': 'passport photos',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('card_number', models.CharField(max_length=32, unique=True, verbose_name='card number')),
                ('verification_token', models.CharField(help_text='Secure token embedded in the QR code — never a student ID.', max_length=128, unique=True, verbose_name='verification token')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('photo_required', 'Photo required'), ('photo_pending', 'Photo pending'), ('ready', 'Ready'), ('generated', 'Generated'), ('printed', 'Printed'), ('issued', 'Issued'), ('active', 'Active'), ('expired', 'Expired'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('replaced', 'Replaced'), ('cancelled', 'Cancelled')], db_index=True, default='ready', max_length=20, verbose_name='status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generated at')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='printed at')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='issued at')),
                ('replacement_reason', models.CharField(blank=True, choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('name_change', 'Name change'), ('student_id_change', 'Student ID change'), ('programme_change', 'Programme / department change'), ('security', 'Security issue'), ('other', 'Other')], max_length=30, verbose_name='replacement reason')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='cancel reason')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='academics.institution', verbose_name='institution')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards_issued', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards_printed', to=settings.AUTH_USER_MODEL, verbose_name='printed by')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='Set on the old card when a replacement card is issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_of_cards', to='id_cards.idcard', verbose_name='replaced by')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='id_cards.idcardbatch', verbose_name='batch')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='id_cards.idcardtemplate', verbose_name='template')),
                ('photo', models.ForeignKey(blank=True, help_text='The approved photo used when the card was generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='id_cards.passportphoto', verbose_name='photo snapshot')),
            ],
            options={
                'verbose_name': 'ID card',
                'verbose_name_plural': 'ID cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reason', models.CharField(choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('name_change', 'Name change'), ('student_id_change', 'Student ID change'), ('programme_change', 'Programme / department change'), ('security', 'Security issue'), ('other', 'Other')], max_length=30, verbose_name='reason')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='id_cards.idcard', verbose_name='card to replace')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_replacement_requests', to='academics.institution', verbose_name='institution')),
                ('replacement_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_via_request', to='id_cards.idcard', verbose_name='replacement card')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_replacements_requested', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_replacement_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='id_replacement_requests', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'replacement request',
                'verbose_name_plural': 'replacement requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('photo_uploaded', 'Photo uploaded'), ('photo_approved', 'Photo approved'), ('photo_rejected', 'Photo rejected'), ('card_generated', 'Card generated'), ('card_printed', 'Card printed'), ('card_issued', 'Card issued'), ('card_replaced', 'Card replaced'), ('card_marked_lost', 'Card marked lost'), ('card_marked_damaged', 'Card marked damaged'), ('card_cancelled', 'Card cancelled'), ('card_expired', 'Card expired'), ('card_verified', 'Card verified (public)'), ('template_changed', 'Template changed'), ('template_created', 'Template created'), ('template_activated', 'Template activated'), ('template_archived', 'Template archived'), ('template_duplicated', 'Template duplicated'), ('batch_generated', 'Batch generated'), ('batch_downloaded', 'Batch downloaded'), ('batch_archived', 'Batch archived'), ('replacement_requested', 'Replacement requested'), ('replacement_approved', 'Replacement approved'), ('replacement_rejected', 'Replacement rejected'), ('settings_updated', 'Settings updated')], db_index=True, max_length=40, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='id_cards.idcard', verbose_name='card')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='id_cards.idcardbatch', verbose_name='batch')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='id_cards.idcardtemplate', verbose_name='template')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='id_cards.passportphoto', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'ID card audit log',
                'verbose_name_plural': 'ID card audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='id_cards_id_created_4f6a4a_idx'), models.Index(fields=['card', '-created_at'], name='id_cards_id_card_id_bad660_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['status'], name='id_cards_id_status_74e85b_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['expiry_date'], name='id_cards_id_expiry__adb24f_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['institution', 'status'], name='id_cards_id_institu_75a38a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['student', 'status'], name='id_cards_id_student_640790_idx'),
        ),
        migrations.AddConstraint(
            model_name='idcard',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'photo_required', 'photo_pending', 'ready', 'generated', 'printed', 'issued', 'active', 'expired', 'lost', 'damaged', 'replaced', 'cancelled'])), name='id_cards_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='idcard',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('ready', 'generated', 'printed', 'issued', 'active'))), fields=('student',), name='uniq_live_card_per_student'),
        ),
        migrations.AddIndex(
            model_name='replacementrequest',
            index=models.Index(fields=['status'], name='id_cards_re_status_c9cd3a_idx'),
        ),
    ]
