# Generated by Django 5.2.14 on 2026-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_hostel_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelallocation',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
