# Generated by Django 5.2.14 on 2026-09-12 15:57
# Manually flattened: SQLite's table rebuild fails when RemoveField drops a
# column still referenced by unique_together. Deleting the models directly is
# equivalent (DROP TABLE drops those columns) and avoids the rebuild.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_hostel_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelApplication',
        ),
        migrations.DeleteModel(
            name='HostelAllocation',
        ),
        migrations.DeleteModel(
            name='HostelRoom',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]