# Generated by Django 5.2.14 on 2026-05-28 09:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='session name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='current session')),
            ],
            options={
                'verbose_name': 'academic session',
                'verbose_name_plural': 'academic sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('lecturer', 'Lecturer'), ('tutor', 'Tutor / Lab Instructor'), ('assistant', 'Teaching Assistant')], default='lecturer', max_length=15, verbose_name='allocation role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'course allocation',
                'verbose_name_plural': 'course allocations',
                'ordering': ['-offering__semester__session__start_date', 'teacher__last_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('venue', models.CharField(blank=True, max_length=100, verbose_name='venue / room')),
                ('max_students', models.PositiveSmallIntegerField(default=50, verbose_name='max enrolment')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'course offering',
                'verbose_name_plural': 'course offerings',
                'ordering': ['-semester__session__start_date', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['faculty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='active', max_length=15, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enrolled at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'enrolment',
                'verbose_name_plural': 'enrolments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='short name / acronym')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/logos/', verbose_name='logo')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('motto', models.CharField(blank=True, max_length=255, verbose_name='motto')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('program_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('professional', 'Professional'), ('doctorate', 'Doctorate')], default='undergraduate', max_length=20, verbose_name='program type')),
                ('duration_years', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='duration (years)')),
                ('total_credits', models.PositiveSmallIntegerField(default=120, verbose_name='total credits required')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hod_approved', 'HOD Approved'), ('finalized', 'Finalized')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='HOD approved at')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalized at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'result sheet',
                'verbose_name_plural': 'result sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer / Third Term')], default='first', max_length=10, verbose_name='semester')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='current semester')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
                'ordering': ['-session__start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('student_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='student ID number')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='admission date')),
                ('expected_graduation', models.DateField(blank=True, null=True, verbose_name='expected graduation')),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='cumulative GPA')),
                ('total_credits_earned', models.PositiveSmallIntegerField(default=0, verbose_name='total credits earned')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'student academic profile',
                'verbose_name_plural': 'student academic profiles',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_primary', models.BooleanField(default=True, verbose_name='primary department')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'teacher–department link',
                'verbose_name_plural': 'teacher–department links',
                'ordering': ['teacher__last_name', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='course code')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('course_type', models.CharField(choices=[('core', 'Core / Compulsory'), ('elective', 'Elective'), ('general', 'General Education'), ('lab', 'Laboratory / Practical'), ('project', 'Project / Dissertation'), ('internship', 'Internship / Industrial')], default='core', max_length=15, verbose_name='type')),
                ('credit_units', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='credit units')),
                ('lecture_hours_per_week', models.PositiveSmallIntegerField(default=3, verbose_name='lecture hours / week')),
                ('lab_hours_per_week', models.PositiveSmallIntegerField(default=0, verbose_name='lab hours / week')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='academics.course', verbose_name='prerequisites')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['code'],
            },
        ),
    ]
