# Generated by Django 5.2.14 on 2026-05-28 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL, verbose_name='allocated by'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.courseoffering', verbose_name='course offering'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of', to=settings.AUTH_USER_MODEL, verbose_name='head of department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department', verbose_name='owning department'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='academics.courseoffering', verbose_name='course offering'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_dean_of', to=settings.AUTH_USER_MODEL, verbose_name='dean'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academics.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.level', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='level',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='department',
            field=models.ForeignKey(help_text="Copied from the course's owning department on creation.", on_delete=django.db.models.deletion.PROTECT, related_name='result_sheets', to='academics.department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_finalized_sheets', to=settings.AUTH_USER_MODEL, verbose_name='finalized by'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_hod_approvals', to=settings.AUTH_USER_MODEL, verbose_name='HOD approved by'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sheets', to='academics.courseoffering', verbose_name='course offering'),
        ),
        migrations.AddField(
            model_name='resultsheet',
            name='submitted_by',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='academics_result_sheets_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicsession', verbose_name='academic session'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.semester', verbose_name='semester'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academics.level', verbose_name='current level'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='teacherdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_memberships', to='academics.department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='teacherdepartment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('offering', 'teacher', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('student', 'offering')},
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('program', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='resultsheet',
            unique_together={('offering', 'submitted_by')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('session', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherdepartment',
            unique_together={('teacher', 'department')},
        ),
    ]
