# Generated by Django 5.1.15 on 2026-06-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='departments',
            field=models.ManyToManyField(related_name='offerings', to='academics.department', verbose_name='departments'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='level_name',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default='100', max_length=3, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='academics.level', verbose_name='level'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester', 'level_name')},
        ),
    ]
