# Generated by Django 5.1.15 on 2026-06-21 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_courseoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='is_retake',
            field=models.BooleanField(default=False, verbose_name='retake'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='original_enrolment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retake_enrolments', to='academics.enrolment', verbose_name='original enrolment'),
        ),
    ]
