# Generated by Django 5.2.14 on 2026-09-17 11:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrolment_is_retake_enrolment_original_enrolment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="Stable machine key, e.g. 'standard'.", max_length=30, unique=True, verbose_name='scheme name')),
                ('label', models.CharField(max_length=80, verbose_name='display label')),
                ('ca_weight', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='CA weight (%)')),
                ('exam_weight', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='exam weight (%)')),
                ('is_default', models.BooleanField(default=False, help_text='Scheme used when no specific scheme is requested.', verbose_name='default scheme')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'grading scheme',
                'verbose_name_plural': 'grading schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('min_cgpa_to_advance', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='minimum CGPA to advance')),
                ('probation_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Session GPA below this places the student on probation.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='probation threshold')),
                ('withdraw_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Session GPA below this triggers withdrawal.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='withdrawal threshold')),
                ('max_failed_per_year', models.PositiveSmallIntegerField(default=2, help_text='More failed courses than this forces a repeat level.', verbose_name='max failed courses per year')),
                ('min_credits_per_year', models.PositiveSmallIntegerField(default=30, help_text='Minimum session credit load expected. Used for diagnostics.', verbose_name='minimum credits per year')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('program', models.OneToOneField(blank=True, help_text='Leave blank for the institution-wide default policy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progression_policy', to='academics.program', verbose_name='program')),
            ],
            options={
                'verbose_name': 'progression policy',
                'verbose_name_plural': 'progression policies',
                'ordering': ['program'],
            },
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('grade', models.CharField(db_index=True, help_text='e.g. A+, A, B-, F', max_length=3, verbose_name='letter grade')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='min score (inclusive)')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for the top band (no upper bound).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='max score (exclusive)')),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='grade point')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='academics.gradingscheme', verbose_name='scheme')),
            ],
            options={
                'verbose_name': 'grade boundary',
                'verbose_name_plural': 'grade boundaries',
                'ordering': ['scheme', '-min_score'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_score__isnull', True), ('min_score__lt', models.F('max_score')), _connector='OR'), name='boundary_min_lt_max')],
                'unique_together': {('scheme', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='GraduationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='CGPA at graduation')),
                ('total_credits', models.PositiveSmallIntegerField(default=0, verbose_name='total credits earned')),
                ('eligible', models.BooleanField(default=False, verbose_name='eligible')),
                ('award_class', models.CharField(blank=True, choices=[('first', 'First Class Honours'), ('second_upper', 'Second Class Upper Division'), ('second_lower', 'Second Class Lower Division'), ('third', 'Third Class'), ('pass', 'Pass / Ordinary'), ('not_awarded', 'Not awarded')], max_length=14, verbose_name='award class')),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('confirmed', 'Confirmed eligible'), ('rejected', 'Rejected'), ('awarded', 'Degree awarded')], default='pending', max_length=10, verbose_name='status')),
                ('reasons', models.TextField(blank=True, verbose_name='reasons')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('level_at_graduation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduations', to='academics.level', verbose_name='level at graduation')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='academics.program', verbose_name='program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='academics.academicsession', verbose_name='completing session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'graduation record',
                'verbose_name_plural': 'graduation records',
                'ordering': ['-session__start_date', 'student__last_name'],
                'unique_together': {('student', 'program', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('decision', models.CharField(choices=[('advance', 'Advance'), ('probation', 'Probation'), ('repeat', 'Repeat level'), ('withdrawn', 'Withdrawn'), ('deferred', 'Deferred'), ('completed', 'Completed / graduation eligible')], default='advance', max_length=12, verbose_name='decision')),
                ('session_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='session GPA')),
                ('cgpa_at_decision', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='CGPA at decision')),
                ('credits_earned', models.PositiveSmallIntegerField(default=0, verbose_name='session credits earned')),
                ('reasons', models.TextField(blank=True, verbose_name='reasons')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('level_at_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_entries', to='academics.level', verbose_name='level at decision')),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_level_students', to='academics.level', verbose_name='next level')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='academics.academicsession', verbose_name='academic session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_statuses', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'student academic status',
                'verbose_name_plural': 'student academic statuses',
                'ordering': ['-session__start_date', 'student__last_name'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
